Fix incremental -a auto-retry case when OLD snapshot is missing

diff --git a/btrfs-backup/btrfs-backup b/btrfs-backup/btrfs-backup
--- a/btrfs-backup/btrfs-backup
+++ b/btrfs-backup/btrfs-backup
@@ -51,7 +51,7 @@ do_backup_full() {
 	echo "Doing full backup"
 	echo "Source: ${SRC}"
 	echo "Destination: ${DST}"
-	ionice -c 3 nice -10 btrfs send  "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Full backup successful" 
+	ionice -c 3 nice -10 btrfs send  "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Full backup successful" || echo "Full backup FAILED" && return 1
 }
 
 do_backup_inc() {
@@ -66,7 +66,7 @@ do_backup_inc() {
 	echo "Old snapshot: ${OLD}"
         echo "Destination: ${DST}"
 
-	ionice -c 3 nice -10 btrfs send -p "${OLD}" "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Incremental backup successful"
+	ionice -c 3 nice -10 btrfs send -p "${OLD}" "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Incremental backup successful" || echo "Incremental backup FAILED" && return 1
 }
 
 get_date_sfx() {
@@ -172,15 +172,17 @@ unset FAILED
 
 ## Of -o is set
 if [ -n "${OLD}" ]; then
-	echo "Making an incremental snapshot... pausing for 3 secs"
-	do_pause 3
+	# echo "Making an incremental snapshot... pausing for 3 secs"
+	# do_pause 3
 
-	do_backup_inc "${SRC}" "${OLD}" "${DST_DIR}" || FAILED="TRUE"
-
-	[ -n "${FAILED}" ] && echo "Incremental backup failed"
+	if [ -d "${OLD}" ]; then
+		do_backup_inc "${SRC}" "${OLD}" "${DST_DIR}" || FAILED="TRUE"
+	else
+		FAILED="TRUE"
+	fi
 fi
 
-if [ -z "${OLD}" ] || [ -n "${FAILED}" -a -n "${AUTO_RETRY}" ]; then
+if [ -z "${OLD}" ] || [[ -n "${FAILED}" && -n "${AUTO_RETRY}" ]]; then
 	unset FAILED
 	echo "Making a full backup"
 	do_pause 3
