WIP v2

diff --git a/btrfs-backup/btrfs-backup b/btrfs-backup/btrfs-backup
--- a/btrfs-backup/btrfs-backup
+++ b/btrfs-backup/btrfs-backup
@@ -13,6 +13,9 @@ help() {
 	echo -e "\t-h\tDisplay help"
 	echo -e "\t-o\tOld snapshot"
 	echo -e "\t-d\tAdd date suffix"
+	echo -e "\t-t\tAdd datetime suffix"
+	echo -e "\t-a\tRetry full backup automatically"
+	echo -e "\t-r\tRemove old source snapshot"
 
 	exit 0
 }
@@ -27,9 +30,40 @@ get_rand() {
 	cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 4 | head -n 1 
 }
 
+do_pause() {
+	SECS=$1
+	[[ $SECS =~ ^-?[0-9]+$ ]] || error "do_pause(): non-integer param given"
+	for ((i = 0 ; i <= $SECS ; i++)); do
+		printf "."
+		sleep 1
+	done
+}
+
+do_backup_full() {
+	if (( $# != 2 )); then
+    		help
+	fi
+	SRC="$0"
+	DST="$1"
+	ionice -c 3 nice -10 btrfs send  "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" 
+}
+
+do_backup_inc() {
+	if (( $# != 3 )); then
+    		help
+	fi
+	SRC="$0"
+	OLD="$1"
+	DST="$2"
+	ionice -c 3 nice -10 btrfs send -p "${OLD}" "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" 
+}
+
+
 ## Params
-DO_HELP=0
-OLD=""
+unset OLD
+unset DO_HELP
+unset AUTO_RETRY
+unset REMOVE
 ADD_DATE_SFX=0
 ADD_TIME_SFX=0
 SFX=""
@@ -38,12 +72,15 @@ if (( $# < 2 )); then
     help
 fi
 
-while getopts 'hdts:o:' option
+while getopts 'hadtrs:o:' option
 do
     case "$option" in
     h)
          help
          ;;
+    a)
+	AUTO_RETRY=1
+	;;
     d)
          ADD_DATE_SFX=1
          ;;
@@ -51,6 +88,9 @@ do
          ADD_DATE_SFX=1
          ADD_TIME_SFX=1
          ;;
+    r)
+	REMOVE=1
+	;;
     s)
          SFX="${OPTARG}"
          ;;
@@ -81,24 +121,47 @@ SRC="$1"
 DST_DIR="$2"
 BASENAME="$(basename ${SRC})"
 
-
-[ -d "${SRC}_${OLD}" ] 	|| { error "Old source subvolume ${SRC}_${OLD} not found"; } 
-[ -d "${SRC}_${NEW}" ] 	&& { echo "SRC: ${SRC}"; }	  || { error "New source subvolume ${SRC}_${NEW} not found"; } 
-[ -d "${DST_DIR}" ]  	&& { echo "DST_DIR: ${DST_DIR}";} || { error "Destination directory ${DST_DIR} not found"; } 
+#### Test parameters
+[ -d "${SRC}" ] &&  { echo "Source: ${SRC}" } || {  error "Source subvolume not found: ${SRC}"}
+## Test for -o $OLD exists
+[ -z ${OLD+x} -o  -d "${OLD}" ] || { error  "Old source subvolume -o defined, but \"${OLD}\" not found" ;}
+[ -d "${DST_DIR}" ] && { echo "Destination: ${DST_DIR}";} || { error "Destination directory ${DST_DIR} not found"; } 
 
 sync
 
-FAILED="false"
+unset FAILED
 
-echo "Trying to make incremental snapshot... pausing for 5 sec"
-sleep 5
+## Of -o is set
+if [ ! -z ${OLD+x} ]; then
+	echo "Trying to make incremental snapshot... pausing for 3 secs"
+	do_pause 3
 
-ionice -c 3 nice -10 btrfs send -p "${SRC}_${OLD}" "${SRC}_${NEW}" | ionice -c 3 nice -10 btrfs receive "${DST_DIR}" || FAILED="true"
+	do_backup_inc "${SRC}" "${OLD}" "${DST_DIR}" &&  echo "Incremental backup successful" || FAILED="TRUE"
 
-BACKUP_NEW="${DST_DIR}/${BASENAME}_${NEW}"
+	[ ! -z {FAILED+x} ] && echo "Incremental backup failed"
+fi
 
-if [ ${FAILED} = "true" ]; then
-	echo "incremental backup failed"
+if [ -z ${OLD+x} ] || [ ! -z ${FAILED} -a ! -z ${AUTO_RETRY} ]; then
+	unset FAILED
+	echo "Trying to make full backup"
+	do_pause 3
+	do_backup_full "${SRC}" "${DST_DIR}" && echo "Full backup successful" || FAILED="TRUE"
+fi
+
+if [ -z ${FAILED} ]; then
+	BACKUP_NEW="${DST_DIR}/${BASENAME}"
+
+
+else
+	error "btrfs backup FAILED"
+fi
+
+#### END
+
+
+
+if [ ! -z ${OLD+x} -a ! -z ${FAILED+x} ]; then
+	echo "Incremental backup failed"
 	if [ -d "$BACKUP_NEW" ]; then
 		echo "Removing failed backup: ${BACKUP_NEW}"
 		btrfs subvolume delete "${BACKUP_NEW}"
