tupa-utils: debug() added, debugging f2b-honeypot

diff --git a/tupa-utils b/tupa-utils
--- a/tupa-utils
+++ b/tupa-utils
@@ -3,7 +3,13 @@
 
 error() {
         MSG=$1
-        echo "${MSG}"
+        echo "Error: ${MSG}"
+        exit 1
+}
+
+debug() {
+        MSG=$1
+        echo "Debug: ${MSG}"
         exit 1
 }
 
