-c check implemented

diff --git a/cfv/cfv b/cfv/cfv
--- a/cfv/cfv
+++ b/cfv/cfv
@@ -8,13 +8,14 @@ TUPA_UTILS="$(dirname "${0}")/tupa-utils"
 
 
 help() {
-    echo "Usage: $(basename "$0") [-hcuA] [-s FILE] DIR [DIR1 ...]"
+    echo "Usage: $(basename "$0") [-hqdcum] [-b DIR] DIR [DIR1 ...]"
     echo -e "\t-h\t\tDisplay help"
     echo -e "\t-q\t\tDo not print checksums"
     echo -e "\t-c\t\tCheck existing checksums"
-    echo -e "\t-u\t\tUpdate missing checksums"
-    echo -e "\t-U\t\tUpdate checksums"
+    echo -e "\t-m\t\tUpdate missing checksums"
+    echo -e "\t-u\t\tUpdate changed checksums"
     echo -e "\t-d\t\tAdd date to previous checksum version"
+    echo -e "\t-b DIR\tBase directory for the operations"
 #    echo -e "\t-A FILE\tFilename for aggregate file"
     exit 0
 }
@@ -29,14 +30,14 @@ if [ ${#} -eq 0 ]; then
 fi
 
 MODE="create"
-QUIET=
+QUIET=""
 BASEDIR=
 DATE=
 CHECKSUM=".checksum"
 
 declare -a ALGO
 
-while getopts 'hqcduUa:b:' option
+while getopts 'hqdcumb:a:' option
 do
 # shellcheck disable=SC2220
     case "$option" in
@@ -44,16 +45,16 @@ do
          help
          ;;
     q)
-        QUIET="yes"
+        QUIET="--quiet"
         ;;
     c)
         MODE="check"
          ;;
+    m)
+        MODE="missing"
+         ;;
     u)
         MODE="update"
-         ;;
-    U)
-        MODE="compare_update"
          ;;
     d)
         DATE="yes"
@@ -105,37 +106,46 @@ if [ -n "${BASEDIR}" ]; then
 fi
 
 set -u
-if [ "${MODE}" = "create" ] || [ "${MODE}" = "update" ]; then
-	for dir in "${DIRS[@]}"; do
-		# cd "${dir}" || continue
-		while read -r d; do
-			pushd "${d}"  > /dev/null || continue
-			if [ -n "${QUIET}" ]; then
-				echo "${d}"
-			else
-				echo "## ${d}"
+for dir in "${DIRS[@]}"; do
+	# cd "${dir}" || continue
+	while read -r d; do
+		pushd "${d}"  > /dev/null || continue
+		echo "# Directory: ${d}"
+		for alg in "${ALGO[@]}"; do
+			CHECKSUM_FILE="${CHECKSUM}.${alg}"
+			if  [ "${MODE}" = "update" ] && [ -s "${CHECKSUM_FILE}" ]; then
+				verbose "${d} : Skipping"
+				continue
 			fi
-			for alg in "${ALGO[@]}"; do
-				CHECKSUM_FILE="${CHECKSUM}.${alg}"
-				if  [ "${MODE}" = "update" ] && [ -s "${CHECKSUM_FILE}" ]; then
-					verbose "${d} : Skipping"
-					continue
-				fi
 
-				if [ -n "${QUIET}" ]; then
-					find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- > "${CHECKSUM}.tmp"
+			if [ "${MODE}" = "check" ]; then
+ 				if [ -n "${QUIET}" ]; then
+					"${alg}sum"  --check --quiet "${CHECKSUM_FILE}"
 				else
-					find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- | tee "${CHECKSUM}.tmp"
+					"${alg}sum"  --check "${CHECKSUM_FILE}"
 				fi
-				if [ -n "${DATE}" ] && [ -f "${CHECKSUM_FILE}" ]; then 
-					mv "${CHECKSUM_FILE}" "${CHECKSUM_FILE}_$(file_modified "${CHECKSUM_FILE}")"
-				fi
-				mv "${CHECKSUM}.tmp" "${CHECKSUM_FILE}"
-			done
-			popd > /dev/null || error "Could not return to dir"
-		done < <(find  "${dir}" -type d)
-	done
-fi
+				continue
+			elif [ -n "${QUIET}" ] ||[ "${MODE}" = "update" ]; then
+				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- > "${CHECKSUM}.tmp"
+			else
+				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- | tee "${CHECKSUM}.tmp"
+			fi
+
+			if [ "${MODE}" = "update" ] && [ -f "${CHECKSUM_FILE}" ]; then
+				# keep the old checksum file if there isn't any difference
+				diff "${CHECKSUM_FILE}" "${CHECKSUM}.tmp" && continue
+			fi
+
+			if [ -n "${DATE}" ] && [ -f "${CHECKSUM_FILE}" ]; then
+				mv "${CHECKSUM_FILE}" "${CHECKSUM_FILE}_$(file_modified "${CHECKSUM_FILE}")"
+			fi
+
+			mv "${CHECKSUM}.tmp" "${CHECKSUM_FILE}"
+
+		done
+		popd > /dev/null || error "Could not return to dir"
+	done < <(find  "${dir}" -type d)
+done
 
 if [ -n "${BASEDIR}" ]; then
 	popd > /dev/null  || error "Could not return to dir"
