proper -u. -m removed. shellchecked

diff --git a/cfv/cfv b/cfv/cfv
--- a/cfv/cfv
+++ b/cfv/cfv
@@ -12,7 +12,7 @@ help() {
     echo -e "\t-h\t\tDisplay help"
     echo -e "\t-q\t\tDo not print checksums"
     echo -e "\t-c\t\tCheck existing checksums"
-    echo -e "\t-m\t\tUpdate missing checksums"
+#    echo -e "\t-m\t\tUpdate missing checksums"
     echo -e "\t-u\t\tUpdate changed checksums"
     echo -e "\t-d\t\tAdd date to previous checksum version"
     echo -e "\t-b DIR\tBase directory for the operations"
@@ -20,9 +20,15 @@ help() {
     exit 0
 }
 
-file_modified() {
-	FILE="${1}"
-	date -r "${FILE}" +"%Y%m%d"
+# Print file modification time
+file_mdate() {
+	date -r "${1}" +"%Y%m%d"
+}
+
+
+# print the files present in a checksum file in sorted order
+chksum_files() {
+	sed -E 's/([0-9a-f]+)[[:blank:]]+(.+)/\2/' -- "${1}" | sort
 }
 
 if [ ${#} -eq 0 ]; then
@@ -37,7 +43,7 @@ CHECKSUM=".checksum"
 
 declare -a ALGO
 
-while getopts 'hqdcumb:a:' option
+while getopts 'hqdcub:a:' option
 do
 # shellcheck disable=SC2220
     case "$option" in
@@ -49,9 +55,6 @@ do
         ;;
     c)
         MODE="check"
-         ;;
-    m)
-        MODE="missing"
          ;;
     u)
         MODE="update"
@@ -106,6 +109,15 @@ if [ -n "${BASEDIR}" ]; then
 fi
 
 set -u
+
+## TODO
+# New logic: 
+# -u: append files not in chksum, remove chksums from missing files
+# -m: remove param
+
+
+# shellcheck disable=SC2094
+
 for dir in "${DIRS[@]}"; do
 	# cd "${dir}" || continue
 	while read -r d; do
@@ -113,13 +125,14 @@ for dir in "${DIRS[@]}"; do
 		echo "# Directory: ${d}"
 		for alg in "${ALGO[@]}"; do
 			CHECKSUM_FILE="${CHECKSUM}.${alg}"
-			if  [ "${MODE}" = "missing" ] && [ -s "${CHECKSUM_FILE}" ]; then
-				verbose "${d} : Skipping"
-				continue
-			fi
+			CHECKSUM_TMP="${CHECKSUM}.tmp"
+
+			# clear previous interrupted run. Does not support parallel operation
+			[ -f "${CHECKSUM_TMP}" ] && rm "${CHECKSUM_TMP}"
 
 			if [ "${MODE}" = "check" ]; then
- 				if [ -n "${QUIET}" ]; then
+ 				[ -f "${CHECKSUM_FILE}" ] || continue
+				if [ -n "${QUIET}" ]; then
 					"${alg}sum"  --check --quiet "${CHECKSUM_FILE}"
 				else
 					"${alg}sum"  --check "${CHECKSUM_FILE}"
@@ -127,25 +140,48 @@ for dir in "${DIRS[@]}"; do
 				continue
 			fi
 
-			if (( $(find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" | wc -l) == 0)); then
-				[ -f "${CHECKSUM}.tmp" ] && rm "${CHECKSUM}.tmp"
-				touch "${CHECKSUM}.tmp"
-			elif [ -n "${QUIET}" ] ||[ "${MODE}" = "update" ]; then
-				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- > "${CHECKSUM}.tmp"
+			touch "${CHECKSUM_TMP}"
+			if [ "${MODE}" = "update" ] && [ -s "${CHECKSUM_FILE}" ]; then
+
+				# calculate checksum for files IN CHECKSUM_FILEmodified later than then CHECKSUM_FILE
+				while read -r line; do
+					file="$(echo "${line}" | sed -E 's/([0-9a-f]+)[[:blank:]]+(.+)/\2/')"
+					if [ -f "${file}" ];then
+						if [ "${file}" -nt "${CHECKSUM_FILE}" ]; then
+							"${alg}sum" -- "${file}" >> "${CHECKSUM_TMP}"
+						else
+							echo "${line}" >> "${CHECKSUM_TMP}"
+						fi
+					fi
+				done < "${CHECKSUM_FILE}"
+
+				# calculate checksums for files not present in CHECKSUM_FILE
+				comm -23 <(find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\n' | sort) \
+					  <( chksum_files  "${CHECKSUM_FILE}"  ) \
+					| xargs -r  "${alg}sum" -- >> "${CHECKSUM_TMP}"
+				# sort in-place
+				sort -k 2 -o "${CHECKSUM_TMP}" "${CHECKSUM_TMP}"
+
+			elif [ -n "${QUIET}" ] || [ "${MODE}" = "update" ]; then
+				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | sort -z | xargs -r -0 "${alg}sum" -- > "${CHECKSUM_TMP}"
 			else
-				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- | tee "${CHECKSUM}.tmp"
+				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | sort -z | xargs -r -0 "${alg}sum" -- | tee "${CHECKSUM_TMP}"
 			fi
 
 			if [ "${MODE}" = "update" ] && [ -f "${CHECKSUM_FILE}" ]; then
 				# keep the old checksum file if there isn't any difference
-				diff "${CHECKSUM_FILE}" "${CHECKSUM}.tmp" && continue
+				diff "${CHECKSUM_FILE}" "${CHECKSUM_TMP}" | grep  '^[<>]'
+				if [ "${PIPESTATUS[0]}" = "0" ]; then
+					rm "${CHECKSUM_TMP}"
+					continue
+				fi
 			fi
 
 			if [ -n "${DATE}" ] && [ -f "${CHECKSUM_FILE}" ]; then
-				mv "${CHECKSUM_FILE}" "${CHECKSUM_FILE}_$(file_modified "${CHECKSUM_FILE}")"
+				mv "${CHECKSUM_FILE}" "${CHECKSUM_FILE}_$(file_mdate "${CHECKSUM_FILE}")"
 			fi
 
-			mv "${CHECKSUM}.tmp" "${CHECKSUM_FILE}"
+			mv "${CHECKSUM_TMP}" "${CHECKSUM_FILE}"
 			# delete empty checksum files
 			[ ! -s "${CHECKSUM_FILE}" ] && rm "${CHECKSUM_FILE}"
 
